package com.example.eicon_dod;

public class Data_meanings {

    public static String sis = "This expression is both sexist, homophobic and transphobic. By calling a man a “sissy”, you’re referring to him as feminine (female-like), “unmanly”, weak and cowardly, as opposed to an apparently strong, brave, “rugged” male specimen…\"";
    public static String mai = "A “maiden” is an outdated term referring to a young (teenage-ish), “innocently naïve” unmarried woman (usually a virgin). This old-fashioned term implies women should be married at a young age and that women above a certain age are “past it”. No. Women have the right to get married whenever they like and should not be defined by their marital status.";
    public static String whi = "Significant others who listen to each other and on occasion, cater to each other's whims—sounds like a pretty positive, healthy relationship. A man shouldn't be made to feel \"less masculine\" by being respectful of his wife or girlfriend.";
    public static String jipgyp = "The word is derived from the word “gypsy”, which in itself is seen as a derogatory term to describe the Romani people, or people from Eastern Europe more broadly. According to NPR, the term was derived from “the popular experience with thieving Gypsies”.";
    public static String bug = "This word’s roots are traced to Bulgarians and anal sex. “Bulgarus” was a name given to a sect of heretics believed to have come from Bulgaria in the 11th century. Over time and through various languages, this was later shortened to “Bugger”. Bet you didn’t see that one coming.";
    public static String Lame = "Lame\" was originally used in reference to people with reduced mobility due to physical disability. The word is now tossed around schoolyards and workplaces everywhere to mean \"uncool\" and \"unappealing.\" Even singer-songwriter Ellie Goulding recently included the word in an activist-oriented tweet addressing misogyny in song lyrics.";
    public static String Retarded = "We all really need to relinquish the R-word. To catch you up to speed, the term \"mental retardation\" is a stale, clinical term once used to label what we now call intellectual disabilities. Using the term to mean \"stupid\" devalues those with intellectual disabilities, which should make you question your word choice.";
    public static String colored = "Sure, this is an older term that doesn't lurk in our language all too often, but it's definitely not just a vocab issue for out-of-touch, elder generations. Actor Benedict Cumberbatch was rightfully criticized earlier this year for using the term \"colored\" while advocating for diversity in film during an interview. (No, the irony is not lost.)";
    public static String OCD = "When you have your desk all nice and tidy, you might be tempted to proclaim yourself \"so OCD.\" But obsessive-compulsive disorder is a mental illness that means so much more than a knack for organization. It means having a lack of control over certain thoughts or activities, so much so that they inhibit daily life.Try using \"particular,\" \"clean\" or \"organized\" instead.";
    public static String Derp = "If you are into Internet lingo, you've seen an overuse of \"herp derp\" or \"derp\" to address Internet faux pas everywhere. It may seem like a quirky phrase that simplifies saying, \"That made no sense,\" or \"What are you even talking about?\" But even before its inception as an Internet meme, it has been consistently used to mock people with intellectual disabilities.";
    public static String crazy = "If you're using the term \"crazy\" countless times a day, you're probably in the norm. But that doesn't mean it's OK. Terms like \"crazy\" — or \"insane,\" for that matter — make light of mental illness in a way no ally wants to support.";
    public static String insane = "If you're using the term \"insane\" countless times a day, you're probably in the norm. But that doesn't mean it's OK. Terms like \"crazy\" — or \"insane,\" for that matter — make light of mental illness in a way no ally wants to support.";
    public static String tranny = "The T-word is never OK for a cisgender person to use. Behind it is a history of violence and oppression inflicted on transgender bodies that we need to recognize, and respect those who continue to overcome it.";
    public static String exotic = "If your new coworker has a name you've never heard of before, hold your tongue before telling him or her it's \"exotic.\" Using this word ends up exoticizing whomever you're referring to, usually with nasty racial underpinnings. It's a major verbal microaggression we need to undo.";
    public static String ghetto = "Suspected to derive from an Italian slang term for waste, the word \"ghetto\" calls back to concentration camps of World War II. But it has also been used to label the neighborhoods marginalized communities were forced to inhabit due to social and economic disadvantage. Classism and racism run rampant when you call a place, or a person, \"ghetto.\" And that should make anyone cringe.";
    public static String uppityy = "This word is often used to describe someone as being arrogant or self-important—like, “Don’t get all uppity on us”—but it has a pretty disturbing history. It was originally a racist term used in the American south to describe black people who didn’t know their place. It was usually part of a two-word descriptor that I’m sure you can guess on your own.";
    public static String miss = "Ms to parallel Mr (except where the woman prefers Miss or Mrs)";
    public static String mrs = "Ms to parallel Mr (except where the woman prefers Miss or Mrs)";
    public static String chairman = "When referring to a position, a quality or an action that might apply to either sex, use a sex neutral term. Also, avoid the use of man or of composite words involving the syllable — man, which imply the term is exclusively male. Use term \"chair\" instead using \"chairman\"";
    public static String clergyman = "When referring to a position, a quality or an action that might apply to either sex, use a sex neutral term. Also, avoid the use of man or of composite words involving the syllable — man, which imply the term is exclusively male. Use term \"members of clergy\" instead using \"clergyman\"";
    public static String foreman = "When referring to a position, a quality or an action that might apply to either sex, use a sex neutral term. Also, avoid the use of man or of composite words involving the syllable — man, which imply the term is exclusively male. Use term \"supervisor\" instead using \"foreman\"";
    public static String mankind = "When referring to a position, a quality or an action that might apply to either sex, use a sex neutral term. Also, avoid the use of man or of composite words involving the syllable — man, which imply the term is exclusively male. Use term \\\"beings/humankind/civilisation/people/human rac\\\" instead using \\\"mankind\"";
    public static String negro = "Oppressed individual usually cast as a powerless scapegoat, regardless of race; very derogatory term for a person of black or African heritage.";
    public static String faggot = "It's a derisive term for homosexual men. It is offensive unless it is used by homosexuals.";
    public static String bap = "It's am acronym for Black American Princess, denoting a black female with an attitude.  It's often seen on license plates.";
    public static String bitch = "It's an uncomplimentary term referring to human female who is perceived as irritable, angry, or cranky. It's usually used by human males in derogatory fashion.";
    public static String jap = "It's a racism word. It can be uncomplimentary shorthand for 'Japanese' or acronym for 'Jewish American Princess', female of Jewish descent with an attitude.";
    public static String coonass = "It's a term used in reference to descendants of French-speaking Louisianans, or Cajuns. Some Cajuns use it with pride and find it inoffensive, while others consider it an ethnic slur.";
    public static String dago = "It means person of Italian descent. It can be derogatory only if it's used by non-Italians.";
    public static String heime = "It means individual of Jewish descent. It is definitely not complimentary.";
    public static String honky = "It's a derisive term for \"white person\", as used by blacks.";
    public static String nappy = "Meaning tight, curly hair.  Generally associated with persons of color, particularly those of black or African descent.  Not particularly derogatory; often used by blacks to refer to hair type.  Often used by black mothers when admonishing their children, as in \"Bring your nappy head in here right now!\"  White school teachers, however, must not use this word.";
    public static String nigger = "Oppressed individual usually cast as a powerless scapegoat, regardless of race; very derogatory term for a person of black or African heritage.";
    public static String kraut = "Not-very-nice word for a person of German descent.  Used frequently in old war movies.";
    public static String hooligan = "It derived from \"Houlihan\", a group of Irish immigrants living in London. It is derogatory to Irish people.";
    public static String vandal = "It means 'dirty godless Germans'. It is offensive to Germans.";
    public static String barbarian = "It means 'stupid jabbering foreigner'. It's a very xenophobic word.";
    public static String cannibal = "It means 'people from the West Indies'. It's a very xenophobic word.";
    public static String gyp = "It means 'filthy Eastern European immigrant'. It's a very xenophobic word.";
    public static String picnic = "This term originated from racism. It means 'to lynch a black person'. Why don't you say \"excursion\" or \"barbecue\" instead?";
    public static String eskimo = "It means 'eaters of raw meat'. Why don't you use \"Inuit\" instead?";
    public static String spaz = "The stigma stems from the word’s association with cerebral palsy, a disease that was once referred to as spastic paralysis.";
    public static String moron = "It means 'a psychological diagnosis denotinf a mild disability', so it is an ableism word.";
    public static String hysteria = "This term's origin is related to sexism. Doctors used this word as a medical explanation for nearly every sick woman they encountered. The idea for such a diagnosis comes from belief that a woman's hysteria is caused by a 'wandering uterus' that is deprived of sexual pleasure.";
    public static String spinster = "It meant a person who spun yard or thread for a living. But it is used to call an unmarried, lower-class woman.";

}
